repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
  
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-redis]
        args: ["--config-file=mypy.ini"]
  
  - repo: local
    hooks:
      - id: check-dependency-injection
        name: Check API Dependency Injection
        entry: python scripts/check_dependency_injection.py
        language: system
        files: ^src/coaching_assistant/api/.*\.py$
        description: Prevents AttributeError from wrong dependency injection in API endpoints