[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "coaching_transcript_tool"
version = "0.1.0"
authors = [
  { name="Your Name", email="you@example.com" }, # 請填寫作者資訊
]
description = "A tool for coaching transcripts" # 請填寫專案描述
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License", # 選擇您的授權條款
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas>=1.3.0",
    "openpyxl>=3.0.9",  # Required for Excel output
    "pytest>=7.0.0",    # For testing
]

[project.urls]
"Homepage" = "https://github.com/howie/coaching_transcript_tool" # 更新為您的 Github Repo URL
"Bug Tracker" = "https://github.com/howie/coaching_transcript_tool/issues" # 更新為您的 Github Repo URL

# [project.scripts]
# my-command = "src.main:main"

[tool.pytest.ini_options]
pythonpath = [
  "src"
]
