"""Add ECPay subscription models

Revision ID: 2484c9c03ec5
Revises: 3d7a3c607c3f
Create Date: 2025-08-18 19:18:32.868134

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2484c9c03ec5"
down_revision: Union[str, Sequence[str], None] = "3d7a3c607c3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_analytics",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_type", sa.String(length=20), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("plan_name", sa.String(length=20), nullable=False),
        sa.Column("plan_changed_during_period", sa.Boolean(), nullable=False),
        sa.Column("previous_plan", sa.String(length=20), nullable=True),
        sa.Column("plan_change_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "total_revenue_usd", sa.DECIMAL(precision=12, scale=4), nullable=False
        ),
        sa.Column(
            "subscription_revenue_usd",
            sa.DECIMAL(precision=12, scale=4),
            nullable=False,
        ),
        sa.Column(
            "usage_overage_usd", sa.DECIMAL(precision=12, scale=4), nullable=False
        ),
        sa.Column(
            "one_time_fees_usd", sa.DECIMAL(precision=12, scale=4), nullable=False
        ),
        sa.Column("sessions_created", sa.Integer(), nullable=False),
        sa.Column("transcriptions_completed", sa.Integer(), nullable=False),
        sa.Column(
            "total_minutes_processed", sa.DECIMAL(precision=10, scale=2), nullable=False
        ),
        sa.Column("unique_active_days", sa.Integer(), nullable=False),
        sa.Column("original_transcriptions", sa.Integer(), nullable=False),
        sa.Column("free_retries", sa.Integer(), nullable=False),
        sa.Column("paid_retranscriptions", sa.Integer(), nullable=False),
        sa.Column("overage_minutes", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column(
            "google_stt_cost_usd", sa.DECIMAL(precision=10, scale=4), nullable=False
        ),
        sa.Column(
            "assemblyai_cost_usd", sa.DECIMAL(precision=10, scale=4), nullable=False
        ),
        sa.Column(
            "total_provider_cost_usd", sa.DECIMAL(precision=10, scale=4), nullable=False
        ),
        sa.Column(
            "plan_utilization_percentage",
            sa.DECIMAL(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column("days_active_in_period", sa.Integer(), nullable=False),
        sa.Column(
            "avg_sessions_per_active_day",
            sa.DECIMAL(precision=8, scale=2),
            nullable=False,
        ),
        sa.Column("churn_risk_score", sa.DECIMAL(precision=3, scale=2), nullable=False),
        sa.Column("exports_by_format", sa.JSON(), nullable=False),
        sa.Column("total_exports", sa.Integer(), nullable=False),
        sa.Column("features_used", sa.JSON(), nullable=False),
        sa.Column("api_calls_made", sa.Integer(), nullable=False),
        sa.Column("user_signup_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_tenure_days", sa.Integer(), nullable=False),
        sa.Column("user_segment", sa.String(length=20), nullable=True),
        sa.Column(
            "avg_processing_time_seconds",
            sa.DECIMAL(precision=8, scale=2),
            nullable=False,
        ),
        sa.Column(
            "success_rate_percentage", sa.DECIMAL(precision=5, scale=2), nullable=False
        ),
        sa.Column("support_tickets_count", sa.Integer(), nullable=False),
        sa.Column("user_timezone", sa.String(length=50), nullable=True),
        sa.Column("user_country", sa.String(length=2), nullable=True),
        sa.Column("user_language", sa.String(length=10), nullable=True),
        sa.Column(
            "predicted_next_month_usage",
            sa.DECIMAL(precision=10, scale=2),
            nullable=False,
        ),
        sa.Column(
            "upgrade_probability", sa.DECIMAL(precision=3, scale=2), nullable=False
        ),
        sa.Column(
            "lifetime_value_estimate", sa.DECIMAL(precision=12, scale=4), nullable=False
        ),
        sa.Column("anomaly_flags", sa.JSON(), nullable=False),
        sa.Column("billing_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "period_type", "period_start", name="uq_billing_analytics_period"
        ),
    )
    op.create_index(
        "idx_billing_analytics_churn_risk",
        "billing_analytics",
        ["churn_risk_score"],
        unique=False,
    )
    op.create_index(
        "idx_billing_analytics_plan", "billing_analytics", ["plan_name"], unique=False
    )
    op.create_index(
        "idx_billing_analytics_recorded",
        "billing_analytics",
        ["recorded_at"],
        unique=False,
    )
    op.create_index(
        "idx_billing_analytics_revenue",
        "billing_analytics",
        ["total_revenue_usd"],
        unique=False,
    )
    op.create_index(
        "idx_billing_analytics_segment",
        "billing_analytics",
        ["user_segment"],
        unique=False,
    )
    op.create_index(
        "idx_billing_analytics_user_period",
        "billing_analytics",
        ["user_id", "period_start"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_billing_analytics_user_period", table_name="billing_analytics")
    op.drop_index("idx_billing_analytics_segment", table_name="billing_analytics")
    op.drop_index("idx_billing_analytics_revenue", table_name="billing_analytics")
    op.drop_index("idx_billing_analytics_recorded", table_name="billing_analytics")
    op.drop_index("idx_billing_analytics_plan", table_name="billing_analytics")
    op.drop_index("idx_billing_analytics_churn_risk", table_name="billing_analytics")
    op.drop_table("billing_analytics")
    # ### end Alembic commands ###
