"""add segment level role assignments

Revision ID: 2961da1deaa6
Revises: e2b8c28f6be2
Create Date: 2025-08-12 21:59:20.840886

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2961da1deaa6"
down_revision: Union[str, Sequence[str], None] = "e2b8c28f6be2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create segment_role table using existing speakerrole enum
    op.create_table(
        "segment_role",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("segment_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                "COACH", "CLIENT", "UNKNOWN", name="speakerrole", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["segment_id"], ["transcript_segment.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "segment_id", name="unique_session_segment_role"
        ),
    )
    op.create_index(
        op.f("ix_segment_role_segment_id"), "segment_role", ["segment_id"], unique=False
    )
    op.create_index(
        op.f("ix_segment_role_session_id"), "segment_role", ["session_id"], unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_segment_role_session_id"), table_name="segment_role")
    op.drop_index(op.f("ix_segment_role_segment_id"), table_name="segment_role")
    op.drop_table("segment_role")
    # ### end Alembic commands ###
