"""add_client_fields_remove_session_source

Revision ID: 6fedb09a97cd
Revises: fee21378d9ca
Create Date: 2025-08-06 07:38:22.159625

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6fedb09a97cd"
down_revision: Union[str, Sequence[str], None] = "fee21378d9ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("client", sa.Column("source", sa.String(length=50), nullable=True))
    op.add_column(
        "client", sa.Column("client_type", sa.String(length=50), nullable=True)
    )
    op.add_column("client", sa.Column("issue_types", sa.Text(), nullable=True))
    op.drop_index(op.f("idx_clients_coach_name"), table_name="client")
    op.drop_index(
        op.f("uq_clients_coach_email"),
        table_name="client",
        postgresql_where="(email IS NOT NULL)",
    )
    op.drop_index(
        op.f("idx_sessions_coach_currency_date"), table_name="coaching_session"
    )
    op.drop_index(op.f("idx_sessions_coach_date"), table_name="coaching_session")
    op.drop_column("coaching_session", "source")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "coaching_session",
        sa.Column(
            "source",
            postgresql.ENUM(
                "CLIENT", "FRIEND", "CLASSMATE", "SUBORDINATE", name="sessionsource"
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("idx_sessions_coach_date"),
        "coaching_session",
        ["coach_id", sa.literal_column("session_date DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_sessions_coach_currency_date"),
        "coaching_session",
        ["coach_id", "fee_currency", "session_date"],
        unique=False,
    )
    op.create_index(
        op.f("uq_clients_coach_email"),
        "client",
        ["coach_id", sa.literal_column("lower('email'::text)")],
        unique=True,
        postgresql_where="(email IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_clients_coach_name"), "client", ["coach_id", "name"], unique=False
    )
    op.drop_column("client", "issue_types")
    op.drop_column("client", "client_type")
    op.drop_column("client", "source")
    # ### end Alembic commands ###
