"""update db schema

Revision ID: 7fcc4672cd15
Revises: 77c28b494ee2
Create Date: 2025-08-05 22:51:27.238863

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7fcc4672cd15"
down_revision: Union[str, Sequence[str], None] = "77c28b494ee2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
