"""add_processing_status_table

Revision ID: b2223a9da505
Revises: 5f8c9d3e2b1a
Create Date: 2025-08-10 10:45:11.324368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2223a9da505'
down_revision: Union[str, Sequence[str], None] = '5f8c9d3e2b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_status',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('duration_processed', sa.Integer(), nullable=True),
    sa.Column('duration_total', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(), nullable=True),
    sa.Column('processing_speed', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_status_session_id'), 'processing_status', ['session_id'], unique=False)
    op.create_index(op.f('ix_processing_status_status'), 'processing_status', ['status'], unique=False)
    op.drop_index(op.f('idx_clients_coach_name'), table_name='client')
    op.drop_index(op.f('idx_sessions_coach_currency_date'), table_name='coaching_session')
    op.drop_index(op.f('idx_sessions_coach_date'), table_name='coaching_session')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_sessions_coach_date'), 'coaching_session', ['coach_id', sa.literal_column('session_date DESC')], unique=False)
    op.create_index(op.f('idx_sessions_coach_currency_date'), 'coaching_session', ['coach_id', 'fee_currency', 'session_date'], unique=False)
    op.create_index(op.f('idx_clients_coach_name'), 'client', ['coach_id', 'name'], unique=False)
    op.drop_index(op.f('ix_processing_status_status'), table_name='processing_status')
    op.drop_index(op.f('ix_processing_status_session_id'), table_name='processing_status')
    op.drop_table('processing_status')
    # ### end Alembic commands ###
