"""fix_profile_photo_url_field_length

Revision ID: e473fb418e6a
Revises: 888cb25741df
Create Date: 2025-08-06 23:42:55.123018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e473fb418e6a'
down_revision: Union[str, Sequence[str], None] = '888cb25741df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coach_profile', 'profile_photo_url',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_coach_profile_id'), table_name='coach_profile')
    op.drop_index(op.f('ix_coaching_plan_id'), table_name='coaching_plan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_coaching_plan_id'), 'coaching_plan', ['id'], unique=False)
    op.create_index(op.f('ix_coach_profile_id'), 'coach_profile', ['id'], unique=False)
    op.alter_column('coach_profile', 'profile_photo_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###
