"""add_clients_and_coaching_sessions_tables

Revision ID: fee21378d9ca
Revises: 7fcc4672cd15
Create Date: 2025-08-06 00:02:31.589522

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fee21378d9ca"
down_revision: Union[str, Sequence[str], None] = "7fcc4672cd15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column("coach_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column("is_anonymized", sa.Boolean(), nullable=False),
        sa.Column("anonymized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["coach_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_client_coach_id"), "client", ["coach_id"], unique=False)
    op.create_index("idx_clients_coach_name", "client", ["coach_id", "name"])
    op.create_index(
        "uq_clients_coach_email",
        "client",
        ["coach_id", sa.func.lower("email")],
        unique=True,
        postgresql_where=sa.text("email IS NOT NULL"),
    )
    op.create_table(
        "coaching_session",
        sa.Column("coach_id", sa.UUID(), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "CLIENT", "FRIEND", "CLASSMATE", "SUBORDINATE", name="sessionsource"
            ),
            nullable=False,
        ),
        sa.Column("duration_min", sa.Integer(), nullable=False),
        sa.Column("fee_currency", sa.String(length=3), nullable=False),
        sa.Column("fee_amount", sa.Integer(), nullable=False),
        sa.Column("transcript_timeseq_id", sa.UUID(), nullable=True),
        sa.Column("audio_timeseq_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("duration_min > 0", name="duration_positive"),
        sa.CheckConstraint("fee_amount >= 0", name="fee_non_negative"),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["coach_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_coaching_session_client_id"),
        "coaching_session",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_coaching_session_coach_id"),
        "coaching_session",
        ["coach_id"],
        unique=False,
    )
    op.create_index(
        "idx_sessions_coach_date",
        "coaching_session",
        ["coach_id", sa.desc("session_date")],
    )
    op.create_index(
        "idx_sessions_coach_currency_date",
        "coaching_session",
        ["coach_id", "fee_currency", "session_date"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_sessions_coach_currency_date", table_name="coaching_session")
    op.drop_index("idx_sessions_coach_date", table_name="coaching_session")
    op.drop_index(op.f("ix_coaching_session_coach_id"), table_name="coaching_session")
    op.drop_index(op.f("ix_coaching_session_client_id"), table_name="coaching_session")
    op.drop_table("coaching_session")
    op.drop_index("uq_clients_coach_email", table_name="client")
    op.drop_index("idx_clients_coach_name", table_name="client")
    op.drop_index(op.f("ix_client_coach_id"), table_name="client")
    op.drop_table("client")
    # ### end Alembic commands ###
