"""add_user_preferences_field

Revision ID: 77c28b494ee2
Revises: 94bae958c238
Create Date: 2025-08-05 21:15:25.185756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c28b494ee2'
down_revision: Union[str, Sequence[str], None] = '94bae958c238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('preferences', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'preferences')
    # ### end Alembic commands ###
