"""Add password support for users

Revision ID: 94bae958c238
Revises: ba3d559ed6c3
Create Date: 2025-08-05 10:31:30.024906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94bae958c238'
down_revision: Union[str, Sequence[str], None] = 'ba3d559ed6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.alter_column('user', 'google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
